In [2]:
import pandas as pd

df=pd.read_csv('/content/sales_dataset.csv')
df.head(1333)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

##**Q1 Dataset Exploration**

Perform the following exploratory steps:

* Display the first 10 rows

* Display the dataset structure using info()

* Find the number of rows and columns

* Identify the data types of each column

In [5]:
# Display the first 10 rows
print("\n--First 10 Row--")
display(df.head(10))

--First 10 Row--

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [8]:
# Display the dataset structure using info()

print("\n--structure using info--")
(df.info())

--structure using info--
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [13]:
#Find the number of rows and columns
print("\n--number of rows and columns--")
df.shape

--number of rows and columns--

(230, 11)

In [12]:
#Identify the data types of each column
print("\n--data types of each column--")
df.dtypes

--data types of each column--

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

##**Q2 Sales Filtering Analysis**

Filter the dataset to display:

* Orders where Sales > 3500

* Orders where Region = "East" and Sales > 2500

Explain what insights you observe.

In [17]:
# Orders where Sales > 3500
sales_above = df[df['Sales'] > 3500]
print("Orders where Sales > 3500")
print(sales_above)

Orders where Sales > 3500
     Order_ID  Order_Date Customer       City Region   Product     Category  \
3        1004  2024-06-06     Sara       Pune   East  Keyboard  Accessories
4        1005  2024-10-15    Rahul  Bangalore  South   Monitor  Electronics
7        1008  2024-03-18    Kavya    Kolkata   East     Phone  Electronics
8        1009  2024-10-31    Kavya  Ahmedabad   East     Phone  Electronics
10       1011  2024-06-30     Neha      Delhi  South   Printer       Office
..        ...         ...      ...        ...    ...       ...          ...
219      1220  2024-03-22    Meera  Bangalore   West     Phone  Electronics
222      1223  2024-03-04    Meera  Ahmedabad  South     Phone  Electronics
223      1224  2024-01-07      Dev  Bangalore   East    Tablet  Electronics
225      1226  2024-06-14    Anita  Ahmedabad   East    Laptop  Electronics
229      1230  2024-04-13    Meera    Kolkata  North   Monitor  Electronics

     Sales  Quantity  Discount   Profit
3     3933         3      0.20   -71.66
4     3550         2      0.20   146.30
7     4693         7      0.05   918.49
8     5071         6      0.10   707.55
10    5977         6      0.00  1578.32
..     ...       ...       ...      ...
219   5986         7      0.05   986.70
222   4356         6      0.10   416.87
223   4115         4      0.05   870.03
225   5647         2      0.15   662.00
229   5087         8      0.10   416.72

[104 rows x 11 columns]

In [18]:
#Orders where Region = "East" and Sales > 2500
sales_above= df[(df['Region'] == 'East') & (df['Sales'] > 2500)]

print("\nOrders where Region = 'East' and Sales > 2500")
print(sales_above)

Orders where Region = 'East' and Sales > 2500
     Order_ID  Order_Date Customer       City Region     Product     Category  \
3        1004  2024-06-06     Sara       Pune   East    Keyboard  Accessories
7        1008  2024-03-18    Kavya    Kolkata   East       Phone  Electronics
8        1009  2024-10-31    Kavya  Ahmedabad   East       Phone  Electronics
13       1014  2024-03-18    Anita  Bangalore   East       Mouse  Accessories
21       1022  2024-01-14    Nitin    Chennai   East     Monitor  Electronics
27       1028  2024-07-21      Dev    Kolkata   East      Tablet  Electronics
33       1034  2024-12-15    Nitin  Ahmedabad   East      Tablet  Electronics
34       1035  2024-02-20    Nitin  Ahmedabad   East      Laptop  Electronics
41       1042  2024-07-15    Rohan    Chennai   East      Laptop  Electronics
43       1044  2024-09-20    Kavya  Hyderabad   East     Printer       Office
52       1053  2024-05-24    Anita    Chennai   East       Phone  Electronics
55       1056  2024-01-03    Sneha    Chennai   East  Headphones  Accessories
58       1059  2024-12-30    Anita      Delhi   East      Tablet  Electronics
60       1061  2024-02-05    Nitin      Delhi   East     Monitor  Electronics
70       1071  2024-05-28    Vikas  Hyderabad   East       Mouse  Accessories
71       1072  2024-05-20    Rahul    Chennai   East     Printer       Office
73       1074  2024-10-10     Sara  Bangalore   East       Mouse  Accessories
74       1075  2024-11-25    Pooja  Ahmedabad   East      Laptop  Electronics
76       1077  2024-03-02     Neha       Pune   East     Monitor  Electronics
81       1082  2024-08-16     Isha    Chennai   East       Phone  Electronics
87       1088  2024-07-29    Pooja     Mumbai   East  Headphones  Accessories
92       1093  2024-01-13    Karan    Kolkata   East      Laptop  Electronics
96       1097  2024-06-07     Isha      Delhi   East       Phone  Electronics
98       1099  2024-07-26    Rahul    Kolkata   East      Laptop  Electronics
108      1109  2024-10-23      Raj  Hyderabad   East      Tablet  Electronics
109      1110  2024-11-28    Priya  Ahmedabad   East     Printer       Office
112      1113  2024-11-01    Meera  Bangalore   East      Tablet  Electronics
113      1114  2024-05-10    Rahul  Bangalore   East       Mouse  Accessories
116      1117  2024-12-07    Pooja    Kolkata   East      Tablet  Electronics
128      1129  2024-06-09    Nitin      Delhi   East      Laptop  Electronics
139      1140  2024-05-04    Karan  Ahmedabad   East     Monitor  Electronics
141      1142  2024-01-01    Rahul     Mumbai   East  Headphones  Accessories
146      1147  2024-05-31      Raj      Delhi   East    Keyboard  Accessories
152      1153  2024-02-27    Rahul     Mumbai   East       Phone  Electronics
156      1157  2024-05-27     Neha    Kolkata   East      Laptop  Electronics
171      1172  2024-09-22     Neha  Hyderabad   East  Headphones  Accessories
179      1180  2024-12-13     Neha  Ahmedabad   East     Monitor  Electronics
182      1183  2024-12-01    Pooja    Chennai   East      Laptop  Electronics
185      1186  2024-03-12    Kavya  Ahmedabad   East       Phone  Electronics
187      1188  2024-07-10     Isha    Kolkata   East       Mouse  Accessories
193      1194  2024-07-23    Pooja      Delhi   East      Laptop  Electronics
197      1198  2024-10-16    Rahul  Ahmedabad   East      Tablet  Electronics
202      1203  2024-05-10    Rahul     Mumbai   East       Phone  Electronics
207      1208  2024-04-29      Dev    Chennai   East     Monitor  Electronics
216      1217  2024-08-16    Karan    Chennai   East     Monitor  Electronics
223      1224  2024-01-07      Dev  Bangalore   East      Tablet  Electronics
225      1226  2024-06-14    Anita  Ahmedabad   East      Laptop  Electronics
228      1229  2024-09-04    Priya       Pune   East      Tablet  Electronics

     Sales  Quantity  Discount   Profit
3     3933         3      0.20   -71.66
7     4693         7      0.05   918.49
8     5071         6      0.10   707.55
13    3616         4      0.05   463.93
21    4827         6      0.05   912.34
27    4054         6      0.00  1013.83
33    4378         2      0.20  -104.30
34    2535         4      0.10   188.15
41    3268         8      0.15   295.15
43    2618         7      0.05   454.64
52    5949         7      0.20   220.44
55    2784         4      0.05   474.60
58    4790         1      0.20   238.53
60    4508         5      0.00   972.35
70    3762         2      0.05   719.68
71    3696         2      0.10   600.75
73    4004         1      0.15   445.81
74    3865         8      0.20   174.96
76    2964         8      0.20   109.33
81    2720         4      0.15   163.13
87    4811         4      0.20   -25.47
92    5372         3      0.15   136.64
96    5096         4      0.15   283.66
98    5674         7      0.05  1141.51
108   2509         4      0.05   371.67
109   2561         4      0.20    57.96
112   4179         5      0.00   754.64
113   3285         3      0.00   625.46
116   3758         5      0.15   446.54
128   5713         3      0.00  1498.02
139   3500         8      0.05   467.16
141   5430         8      0.05   741.25
146   5709         7      0.20   383.58
152   3644         2      0.05   512.25
156   4906         4      0.00  1115.89
171   4228         1      0.20   236.15
179   2690         7      0.10   452.70
182   5884         1      0.05  1266.10
185   5047         2      0.10   564.78
187   4333         8      0.10   667.53
193   3767         7      0.20   103.23
197   3955         1      0.10   284.92
202   2901         8      0.15   252.25
207   3585         7      0.15   287.44
216   2643         5      0.15    78.53
223   4115         4      0.05   870.03
225   5647         2      0.15   662.00
228   2635         8      0.00   531.76

#**Insights**
* Orders with Sales greater than 3500 are high-value transactions and contribute significantly to overall revenue.
* Orders from the East region with Sales greater than 2500 indicate strong sales performance in that region.
* These filters help identify top-performing orders and regions.
* The results can be used to focus marketing efforts and improve business strategies.

##**Q3 Customer Purchase Analysis**

Identify the top 5 customers based on total sales.

Hint: Use GroupBy with aggregation.

In [19]:
#Identify the top 5 customers based on total sales.
customer_sales = df.groupby('Customer')['Sales'].sum()
topcustomers = customer_sales.sort_values(ascending=False).head(5)

print("Top 5 Customers Based on Total Sales:")
print(topcustomers)

Top 5 Customers Based on Total Sales:
Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

##**Q4 Regional Sales Performance**

Calculate the total sales generated by each region.

Then identify:

* Which region generated the highest revenue?

In [22]:
regional_sales = df.groupby('Region')['Sales'].sum()
print("\n --Total Sales by Region:--")
print(regional_sales)

# Find the region with the highest revenue
highest_region = regional_sales.idxmax()
highest_revenue = regional_sales.max()

print("\nRegion with the Highest Revenue:")
print(f"{highest_region} : {highest_revenue}")

 --Total Sales by Region:--
Region
East     232675
North    158210
South    183108
West     170227
Name: Sales, dtype: int64

Region with the Highest Revenue:
East : 232675

##**Q5 Product Performance Analysis**

* Calculate the total quantity sold for each product.

* Which product appears to be the most popular?

In [25]:
# Calculate the total quantity sold for each product.
product_qty = df.groupby('Product')['Quantity'].sum().reset_index()

product_qty_sorted = product_qty.sort_values(by='Quantity', ascending=False)

print("---Total Quantity Sold by Product---")
print(product_qty_sorted.to_string(index=False))

---Total Quantity Sold by Product---
   Product  Quantity
   Monitor       156
     Phone       151
    Tablet       150
    Laptop       140
     Mouse       122
Headphones       115
  Keyboard       110
   Printer       108

In [26]:
# Which product appears to be the most popular?
most_popular = product_qty_sorted.iloc[0]
most_popular_product = most_popular['Product']
total_units = most_popular['Quantity']

print(f"\n★ Most Popular Product: '{most_popular_product}' with a total of {total_units} units sold.")

★ Most Popular Product: 'Monitor' with a total of 156 units sold.

##**Q6 Multi-Level Grouping**

* Group the dataset by: Region and Category

* Calculate the total sales for each combination.

* What insights can you derive from this analysis?

In [27]:
# Group the dataset by: Region and Category
# Calculate the total sales for each combination.

multi_level_sales = df.groupby(['Region', 'Category'])['Sales'].sum().reset_index()
print("--- Total Sales by Region and Category Combination ---")
print(multi_level_sales.to_string(index=False))

--- Total Sales by Region and Category Combination ---
Region    Category  Sales
  East Accessories  57646
  East Electronics 160907
  East      Office  14122
 North Accessories  62052
 North Electronics  70023
 North      Office  26135
 South Accessories  80914
 South Electronics  86690
 South      Office  15504
  West Accessories  64811
  West Electronics  84128
  West      Office  21288

##**Insights**

* Identifies the best-selling category in each region.
* Helps compare category performance across regions.
* Shows which region generates the highest sales.
* Highlights low-performing categories that may need improvement.
* Supports better marketing and inventory planning.

##**Q7 Pivot Table Creation**

Create a pivot table showing:

* Rows → Region

* Columns → Product

* Values → Total Sales

Which region sells the most laptops?

In [29]:
#Pivot Table

pivot_sales = df.pivot_table(
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum',
    fill_value=0
)

print("--- Sales Pivot Table (Region vs Product) ---")
print(pivot_sales)

--- Sales Pivot Table (Region vs Product) ---
Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

In [32]:
#Which region sells the most laptops?
if 'Laptop' in pivot_sales.columns:
    laptop_region = pivot_sales['Laptop'].idxmax()
    laptop_sales = pivot_sales['Laptop'].max()
    print(f"\n sells the most Laptops is: '{laptop_region}' with a total revenue of ${laptop_sales:,}")
else:
    print("\n 'Laptop' column not found in your dataset. Please check your specific product")

 sells the most Laptops is: 'East' with a total revenue of $55,568

##**Q8 Profitability Analysis**

* Calculate the average profit for each product category.

* Which category is most profitable?

In [33]:
# Calculate the average profit for each product category.
category_profit = df.groupby('Category')['Profit'].mean().reset_index()
category_profit_sorted = category_profit.sort_values(by='Profit', ascending=False)

print("---Average Profit by Product Category---")
print(category_profit_sorted.to_string(index=False))

--- Average Profit by Product Category ---
   Category     Profit
     Office 471.938462
Accessories 410.603086
Electronics 396.462114

In [35]:
#  Which category is most profitable?

most_profitable_row = category_profit_sorted.iloc[0]
most_profitable_cat = most_profitable_row['Category']
avg_profit_val = most_profitable_row['Profit']

print(f"\n Most Profitable Category: '{most_profitable_cat}' with an average profit of ${avg_profit_val:,.2f} per order.")

 Most Profitable Category: 'Office' with an average profit of $471.94 per order.

##**Q9 Discount Impact Study**

Analyze the relationship between discount and profit.

Tasks:

* Calculate the average profit for each discount level

* Identify whether higher discounts lead to lower profit

In [36]:

discount_impact = df.groupby('Discount')['Profit'].mean().reset_index()

discount_impact_sorted = discount_impact.sort_values(by='Discount')

print("--- Average Profit by Discount Level ---")
print(discount_impact_sorted.to_string(index=False))

--- Average Profit by Discount Level ---
 Discount     Profit
     0.00 751.210588
     0.05 531.368039
     0.10 346.460513
     0.15 237.191400
     0.20  90.026923

##**Q10 End-to-End Data Wrangling Task**

Perform the following workflow:

1. Filter the dataset where Sales > 3000

 2. Group data by Region and Product

3. Calculate total sales

4. Reshape the result into a pivot table

Explain the business insights obtained from this analysis.

In [48]:
# 1. Filter the dataset where Sales > 3000
high_value_orders = df[df['Sales'] > 3000]
print("--- High-Value Orders ---")
print(high_value_orders)

--- High-Value Orders ---
     Order_ID  Order_Date Customer       City Region   Product     Category  \
3        1004  2024-06-06     Sara       Pune   East  Keyboard  Accessories
4        1005  2024-10-15    Rahul  Bangalore  South   Monitor  Electronics
5        1006  2024-07-04    Pooja  Bangalore   West   Printer       Office
7        1008  2024-03-18    Kavya    Kolkata   East     Phone  Electronics
8        1009  2024-10-31    Kavya  Ahmedabad   East     Phone  Electronics
..        ...         ...      ...        ...    ...       ...          ...
219      1220  2024-03-22    Meera  Bangalore   West     Phone  Electronics
222      1223  2024-03-04    Meera  Ahmedabad  South     Phone  Electronics
223      1224  2024-01-07      Dev  Bangalore   East    Tablet  Electronics
225      1226  2024-06-14    Anita  Ahmedabad   East    Laptop  Electronics
229      1230  2024-04-13    Meera    Kolkata  North   Monitor  Electronics

     Sales  Quantity  Discount  Profit
3     3933         3      0.20  -71.66
4     3550         2      0.20  146.30
5     3073         8      0.20  191.58
7     4693         7      0.05  918.49
8     5071         6      0.10  707.55
..     ...       ...       ...     ...
219   5986         7      0.05  986.70
222   4356         6      0.10  416.87
223   4115         4      0.05  870.03
225   5647         2      0.15  662.00
229   5087         8      0.10  416.72

[115 rows x 11 columns]

In [49]:
# 2 & 3. Group data by Region and Product, then calculate total sales
grouped_sales = high_value_orders.groupby(['Region', 'Product'])['Sales'].sum().reset_index()
discount_impact_sorted = discount_impact.sort_values(by='Discount')

print("--- Average Profit by Discount Level ---")
print(discount_impact_sorted.to_string(index=False))

--- Average Profit by Discount Level ---
 Discount     Profit
     0.00 751.210588
     0.05 531.368039
     0.10 346.460513
     0.15 237.191400
     0.20  90.026923

In [50]:
#4 . Reshape the result into a final pivot table representation
# Rows -> Region, Columns -> Product_Name, Values -> Sales
final_wrangling_pivot = grouped_sales.pivot_table(
    values='Sales',
    index='Region',
    columns='Product',
    fill_value=0)

print("--- Final Reshaped High-Value Sales Pivot Table ---")
print(final_wrangling_pivot)

--- Final Reshaped High-Value Sales Pivot Table ---
Product  Headphones  Keyboard   Laptop  Monitor    Mouse    Phone  Printer  \
Region
East        14469.0    9642.0  44096.0  16420.0  19000.0  29500.0   3696.0
North        5326.0   15653.0   4540.0   5087.0  22209.0  24670.0  17185.0
South       10026.0   19249.0  17950.0  14921.0  26928.0  18218.0  14143.0
West        13898.0   33380.0   5922.0  14354.0   3511.0  15653.0  12648.0

Product   Tablet
Region
East     29229.0
North     3392.0
South    19613.0
West     17185.0